# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Video(object):
    def setupUi(self, Video):
        Video.setObjectName("Video")
        Video.resize(640, 480)
        Video.setMinimumSize(QtCore.QSize(640, 480))
        Video.setMaximumSize(QtCore.QSize(640, 480))
        self.lbl_video = QtWidgets.QLabel(Video)
        self.lbl_video.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.lbl_video.setMinimumSize(QtCore.QSize(640, 480))
        self.lbl_video.setMaximumSize(QtCore.QSize(640, 480))
        self.lbl_video.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video.setObjectName("lbl_video")

        self.retranslateUi(Video)
        QtCore.QMetaObject.connectSlotsByName(Video)

    def retranslateUi(self, Video):
        _translate = QtCore.QCoreApplication.translate
        Video.setWindowTitle(_translate("Video", "视频监控"))
        self.lbl_video.setText(_translate("Video", "视频显示区域"))
